export type IBKRStatus={connected:boolean;authenticated:boolean;established?:boolean;message?:string};
export type IBKRMarketSnapshot={conid:number;conidEx?:string;last?:number;bid?:number;ask?:number;bidSize?:number;askSize?:number;updatedAt?:number;raw:Record<string,unknown>};
const DEFAULT_BASE_URL='https://api.ibkr.com';
function baseUrl(){return(process.env.IBKR_API_URL||DEFAULT_BASE_URL).replace(/\/$/,'');}
function configured(){return Boolean(process.env.IBKR_ACCESS_TOKEN||process.env.IBKR_CLIENT_ASSERTION);}
async function request<T>(path:string,init?:RequestInit):Promise<T>{const headers={Accept:'application/json',...(init?.body?{'Content-Type':'application/json'}:{}),...(process.env.IBKR_ACCESS_TOKEN?{Authorization:'Bearer '+process.env.IBKR_ACCESS_TOKEN}:{}),...(init?.headers??{})};const response=await fetch(baseUrl()+path,{...init,headers,cache:'no-store'});const text=await response.text();let data:unknown=null;try{data=text?JSON.parse(text):null}catch{data={raw:text}}if(!response.ok){const detail=typeof data==='object'&&data!==null&&'message'in data?String((data as {message:unknown}).message):'HTTP '+response.status;throw new Error('IBKR API error: '+detail)}return data as T;}
function num(value:unknown):number|undefined{if(typeof value==='number'&&Number.isFinite(value))return value;if(typeof value==='string'){const parsed=Number(value.replace(/,/g,''));return Number.isFinite(parsed)?parsed:undefined}return undefined;}
export const ibkr={
isConfigured:configured,
async getStatus():Promise<IBKRStatus>{if(!configured())return{connected:false,authenticated:false,established:false,message:'IBKR Web API credentials are not configured.'};try{const data:any=await request('/iserver/auth/status');return{connected:true,authenticated:Boolean(data?.authenticated),established:Boolean(data?.established),message:data?.authenticated?'IBKR Web API session reachable.':'IBKR credentials configured; brokerage session is not authenticated.'}}catch(error){return{connected:false,authenticated:false,established:false,message:error instanceof Error?error.message:'Unable to reach IBKR Web API.'}}},
async getAccounts():Promise<unknown>{return request('/iserver/accounts')},
async searchContract(symbol:string):Promise<unknown>{return request('/iserver/secdef/search?symbol='+encodeURIComponent(symbol.trim().toUpperCase()))},
async getSnapshot(conids:number[],fields=['31','84','85','86','87','88']){if(!conids.length)return[];const data=await request<unknown[]>('/iserver/marketdata/snapshot?conids='+conids.join(',')+'&fields='+fields.join(','));return data.map(row=>{const raw=(row??{}) as Record<string,unknown>;return{conid:num(raw.conid)??0,conidEx:typeof raw.conidEx==='string'?raw.conidEx:undefined,last:num(raw['31']),bid:num(raw['84']),ask:num(raw['86']),bidSize:num(raw['85']),askSize:num(raw['88']),updatedAt:num(raw._updated),raw} satisfies IBKRMarketSnapshot})},
async getHistory(conid:number,period='1y',bar='1d'){const params=new URLSearchParams({conid:String(conid),period,bar,outsideRth:'true'});return request('/iserver/marketdata/history?'+params.toString())},
};