'use client';
import {useEffect,useState} from 'react';
type Overview={account?:{name:string;base_currency:string;account_type:string}|null;positions:Array<{id:string;quantity:number;market_value:number|null;unrealized_pnl:number|null;assets?:{symbol:string}|null}>;signals:Array<{id:string;action:string;confidence:number|null;rationale:string|null;assets?:{symbol:string}|null}>;orders:Array<{id:string;side:string;status:string;quantity:number;assets?:{symbol:string}|null;venues?:{name:string}|null}>;riskRules:Array<{name:string;value:number;unit:string|null}>;tradingMode:string;liveTradingEnabled:boolean};
type Health={configured:boolean;connected?:boolean;authenticated?:boolean;reachable?:boolean;message?:string};
export default function Home(){
 const[data,setData]=useState<Overview|null>(null);const[error,setError]=useState('');const[ibkr,setIbkr]=useState<Health|null>(null);const[kraken,setKraken]=useState<Health|null>(null);
 useEffect(()=>{fetch('/api/trading/overview').then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error??j.status??'Unable to load trading data');setData(j)}).catch(e=>setError(e.message));fetch('/api/brokers/ibkr/health').then(r=>r.json()).then(setIbkr).catch(()=>setIbkr({configured:false,connected:false,authenticated:false,message:'IBKR health check unavailable'}));fetch('/api/brokers/kraken/health').then(r=>r.json()).then(setKraken).catch(()=>setKraken({configured:false,reachable:false,message:'Kraken health check unavailable'}))},[]);
 const portfolio=data?.positions.reduce((s,p)=>s+Number(p.market_value??0),0)??0;const pnl=data?.positions.reduce((s,p)=>s+Number(p.unrealized_pnl??0),0)??0;
 return <main className="shell"><header className="topbar"><div><div className="brand">AI Trading Agent</div><div className="sub">Stocks + Crypto · paper trading</div></div><div className="status"><span className="dot"/>{data?.liveTradingEnabled?'LIVE TRADING ENABLED':'Live trading disabled'}</div></header>
 {error&&<div className="card warning">Database connection is not ready: {error}</div>}
 <section className="grid"><div className="card"><div className="label">Account</div><div className="value">{data?.account?.name??'Not connected'}</div><div className="sub">{data?.tradingMode??'paper'} mode</div></div><div className="card"><div className="label">Position value</div><div className="value">CA {portfolio.toLocaleString(undefined,{maximumFractionDigits:2})}</div><div className="sub">{data?.positions.length??0} positions</div></div><div className="card"><div className="label">Unrealized P&amp;L</div><div className={pnl>=0?'value positive':'value muted'}>{pnl>=0?'+':''}CA {pnl.toLocaleString(undefined,{maximumFractionDigits:2})}</div></div><div className="card"><div className="label">Risk rules</div><div className="value positive">LOCKED</div><div className="sub">{data?.riskRules.length??0} deterministic limits</div></div></section>
 <section className="main"><div className="card"><div className="sectionTitle">AI Signals</div><div className="sub">Signals never bypass deterministic risk controls.</div>{(data?.signals??[]).length===0?<div className="empty">No signals yet. Stock scanning will populate this panel after candles are ingested.</div>:data!.signals.map(s=><div className="row" key={s.id}><div><div className="symbol">{s.assets?.symbol??'Unknown'}</div><div className="sub">{s.rationale??'No rationale'}</div></div><div>{s.action.toUpperCase()} · {s.confidence??0}%</div></div>)}</div><div className="card"><div className="sectionTitle">Paper Orders</div><div className="sub">No live broker orders are permitted.</div>{(data?.orders??[]).length===0?<div className="empty">No paper orders yet.</div>:data!.orders.map(o=><div className="row" key={o.id}><div><div className="symbol">{o.assets?.symbol??'Unknown'}</div><div className="sub">{o.venues?.name??'Unassigned venue'} · {o.quantity}</div></div><div>{o.side.toUpperCase()} · {o.status}</div></div>)}</div></section>
 <section className="card" style={{marginTop:16}}><div className="sectionTitle">Market Data Adapters</div><div className="sub">Broker market data feeds into analysis; order submission remains separately locked.</div><div className="ruleGrid"><div className="rule"><span>IBKR · Stocks/ETFs</span><strong className={ibkr?.authenticated?'positive':'muted'}>{ibkr?.authenticated?'CONNECTED':ibkr?.configured?'NOT AUTHENTICATED':'NOT CONFIGURED'}</strong></div><div className="rule"><span>IBKR connection</span><strong>{ibkr?.connected?'ONLINE':'OFFLINE'}</strong></div><div className="rule"><span>Kraken · Crypto</span><strong className={kraken?.reachable?'positive':'muted'}>{kraken?.reachable?'CONNECTED':'OFFLINE'}</strong></div><div className="rule"><span>Kraken market data</span><strong>{kraken?.reachable?'READY':'UNAVAILABLE'}</strong></div><div className="rule"><span>Order submission</span><strong className="positive">DISABLED</strong></div></div>{(ibkr?.message||kraken?.message)&&<div className="sub" style={{marginTop:10}}>{[ibkr?.message,kraken?.message].filter(Boolean).join(' · ')}</div>}
 <div className="card" style={{marginTop:12}}><div className="sectionTitle">IBKR Market Data</div><div className="sub">Primary stock/ETF feed. Contract discovery and historical data are available through the adapter.</div><div className="ruleGrid"><div className="rule"><span>Configured</span><strong>{ibkr?.configured?'YES':'NO'}</strong></div><div className="rule"><span>Authenticated</span><strong>{ibkr?.authenticated?'YES':'NO'}</strong></div><div className="rule"><span>Trading</span><strong className="positive">LOCKED</strong></div></div></div>
 <div className="card" style={{marginTop:12}}><div className="sectionTitle">Kraken Market Data</div><div className="sub">Crypto market-data feed. Public market data does not require private API credentials. Order submission remains locked.</div><div className="ruleGrid"><div className="rule"><span>API reachable</span><strong>{kraken?.reachable?'YES':'NO'}</strong></div><div className="rule"><span>Market data</span><strong>{kraken?.reachable?'READY':'UNAVAILABLE'}</strong></div><div className="rule"><span>Trading</span><strong className="positive">LOCKED</strong></div></div></div></section>
 <section className="card" style={{marginTop:16}}><div className="sectionTitle">Deterministic Risk Guardrails</div><div className="sub">AI decisions cannot override these limits.</div><div className="ruleGrid">{(data?.riskRules??[]).map(r=><div className="rule" key={r.name}><span>{r.name}</span><strong>{r.value}{r.unit==='percent'?'%':r.unit?' '+r.unit:''}</strong></div>)}</div></section></main>}
